// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByet6M8gjGEVmVgkMxFRYpsJaFbA83dc8',
    appId: '1:847134232688:web:9040e1c775620b6cc1a4b5',
    messagingSenderId: '847134232688',
    projectId: 'verdant-app-105c7',
    authDomain: 'verdant-app-105c7.firebaseapp.com',
    storageBucket: 'verdant-app-105c7.firebasestorage.app',
    measurementId: 'G-XZE8KS6RC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaIqs7oYW9mNoZwh4JpruGw-BRpvN3EdU',
    appId: '1:847134232688:android:c346f83b97a46ea6c1a4b5',
    messagingSenderId: '847134232688',
    projectId: 'verdant-app-105c7',
    storageBucket: 'verdant-app-105c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikMteL_3xnfftsT5JwnntTExsUEnU1rs',
    appId: '1:847134232688:ios:e9416b0677e5c648c1a4b5',
    messagingSenderId: '847134232688',
    projectId: 'verdant-app-105c7',
    storageBucket: 'verdant-app-105c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikMteL_3xnfftsT5JwnntTExsUEnU1rs',
    appId: '1:847134232688:ios:e9416b0677e5c648c1a4b5',
    messagingSenderId: '847134232688',
    projectId: 'verdant-app-105c7',
    storageBucket: 'verdant-app-105c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByet6M8gjGEVmVgkMxFRYpsJaFbA83dc8',
    appId: '1:847134232688:web:89b67454524b471fc1a4b5',
    messagingSenderId: '847134232688',
    projectId: 'verdant-app-105c7',
    authDomain: 'verdant-app-105c7.firebaseapp.com',
    storageBucket: 'verdant-app-105c7.firebasestorage.app',
    measurementId: 'G-379DZNH9WL',
  );
}
